[dotfiles]
ignore = [".git", ".gitignore", "dot.toml"]

[dotfiles.macos]
ignore = [
  ".config/hypr",
  ".config/kanshi",
  ".config/omarchy",
  ".config/fontconfig",
]

[dotfiles.linux]
ignore = [".config/aerospace"]

[git]
name = "LucasCoppola"
email = "lucascoppola21@gmail.com"

[packages]
shared = [
  "neovim",
  "tmux",
  "ripgrep",
  "fzf",
  "jq",
  "bat",
  "zoxide",
  "docker"
]

[packages.linux]
extra = [
  "docker",
  "hypridle",
  "kanshi",
  "ghostty",
  "btop",
  "otf-geist-mono-nerd",
]

[packages.macos]
casks = [
  "docker",
]
